### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by s3rvant** [isamert/scli#1]
Unable to run due to Python error:
 File "scli", line 102
SyntaxError: Non-ASCII character '\xe2' in file scli on line 102, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Also please note that I cannot use "scli -u PHONE" but rather had to use "python scli -u PHONE" though this may just be me missing some step to shorten the command.

**Comment by isamert** [comment]
The error should be fixed now.

To use `scli -u PHONE` you need to give this command:
```
chmod +x scli
```
This will make the file executable. Now you can do: `./scli -u PHONE` in the same folder. To be able to use `scli` from anywhere, you need to move the file somewhere in your `$PATH` variable (like `/usr/local/bin/` etc). I should've been more clear in the README, I'll update it soon.

**Comment by s3rvant** [comment]
Issue is still there and still need "python scli -u PHONE" to use it:

Moved scli-master folder to /usr/local/bin/scli and chmod +x scli

./scli -u PHONE
bash: ./scli: /bin/python: bad interpreter: No such file or directory

python scli -u PHONE
File "scli", line 102
SyntaxError: Non-ASCII character '\xe2' in file scli on line 102, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

I am running Ubuntu 18.04.1

**Comment by isamert** [comment]
Oh, you need python3 to run this script. Install python3 and run this file with `python3` command (or any other command that starts with python3, like `python3.7`). If it's not possible to install python3 for you for some reason, I can make this script python2 compatible but AFAIK nearly every distro has it pre-installed (you also may have it already installed, but it seems like your default one is python2, just try to run the script with python3 command).

**Comment by s3rvant** [comment]
Okay, I was able to get the program to start:
- both program folders were in /usr/local/bin but not in $PATH so I added a symlink in /usr/local/bin
- now I can "which" both programs successfully and run directly like "signal-cli command"
- I still have to prefix "python3" and that requires full path so my command looks like: python3 /usr/local/bin/scli -u PHONE
- this does load the interface and my contacts are listed and I can hit enter to start a conversation and nagivate as expected

however, message I send do not do anything. they just disappear from the typing area and never show up in the conversation and never reach the contact

quitting the program does not display any error messages in the terminal

**Comment by s3rvant** [comment]
> killall java
java: no process found

> scli -u PHONE
  File "/usr/local/bin/scli", line 162
    def exec(state, cmd, args):
           ^
SyntaxError: invalid syntax

> python3 /usr/local/bin/scli -u PHONE
* program launches

new terminal
> signal-cli --dbus send -m "test" PHONE
Missing native library dependency for dbus service: no unix-java in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]

> signal-cli -u PHONE_NUMBER updateAccount
* no output

Retried scli with same issue where messages just disappear without sending

**Comment by isamert** [comment]
Please install `libunixsocket-java` package (assuming you are using ubuntu or debian, on Arch it's `libmatthew-unix-java` from AUR) and see if it works after.

**Comment by s3rvant** [comment]
I can now send messages successfully, however it does not receive. When contact replies my phone gets the message but nothing shows up in scli. On first load after installing the package above the previous messages in conversation loaded however after quitting scli and relaunching it the previous conversation no longer shows.

I ran the signali-cli test command and it does not give any output, however I do not receive the test message on phone or scli.

**Comment by isamert** [comment]
scli does not keep message history although I may add this as an optional feature in near future.

For receiving problem, I added some debugging stuff (I should've done that way earlier). Please update the scli script and run it with `--debug` option, like `scli -u PHONE --debug`. (Also now _probably_ you can just use `scli` without writing `python3` before) It will create a file in your home folder, named `scli.log`. Can you send the output of the log file, after trying to receive a message? (**Warning**: be careful that the output may contain personal info, like your phone number etc. You may want to remove them before posting here)

**Comment by s3rvant** [comment]
Sent 2 messages from scli, received 1 (only showed on phone) and then sent 1 from phone:

ERROR:root:input:b'{"envelope":{"source":"","sourceDevice":0,"relay":null,"timestamp":15486320393$
ERROR:root:'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/bin/scli", line 289, in daemon_handler
    urwid.emit_signal(self, 'receive_message', e['envelope'])
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 265, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 295, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/local/bin/scli", line 554, in on_receive_message
    notif = 'New message from ' + get_contact_name(contact) + ': "' + msg + '"'
  File "/usr/local/bin/scli", line 53, in get_contact_name
    name = x.get('name')
AttributeError: 'NoneType' object has no attribute 'get'
ERROR:root:input:b'{"error":{"message":"org.whispersystems.libsignal.InvalidMessageException: Tim$
ERROR:root:Expecting ',' delimiter: line 1 column 132 (char 131)
Traceback (most recent call last):
  File "/usr/local/bin/scli", line 288, in daemon_handler
    e = json.loads(line)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 132 (char 131)
ERROR:root:input:b',"envelope":{"source":"MY_PHONE","sourceDevice":1,"relay":null,"timestamp"$
ERROR:root:Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/bin/scli", line 288, in daemon_handler
    e = json.loads(line)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by isamert** [comment]
If you send messages from your phone to your phone number, you will not be able to see them in `scli` because signal app does not even send them to servers. But sending to your phone number from `scli` should work(You may need to add your phone number to your contacts list in your phone.) This may help you for debugging.

Another problem is if you send messages from your phone to some contact, scli will not be able to sync those sent messages. It's a limitation of `signal-cli` (I will investigate further if it's possible, but it's probably a limitation as far as I understand)

**Comment by s3rvant** [comment]
I launched scli again and this time just waited to see if it was from trying to sync previous messages and it did indeed crash without me doing anything and log file contained a different incoming message.

Also please note that log file was missing previous contents so logging may be clearing the file at program launch instead of appending to the end.

**Comment by isamert** [comment]
The problem is the message you are receiving does not have a source. I really don't have any idea why and how this happens. I pushed a version that will not crash on this situation (and it will show the message as a notification) but you will not be able to have a conversation. Maybe this is a specific situation to the sender, were you able to test with different senders?

**Comment by s3rvant** [comment]
Okay, after upgrading and launching scli I had several such messages come through of which I recognized as those received from chatting with a couple of my primary contacts today. No clue why there is no sender but I do know personally who the senders were since they were received successfully on my phone.

Right now 2 of my contacts are online so I've tested with them and was able to both send and receive, however the messages they sent were displayed as "Message with no source: MESSAGE" and did not show up in the chat pane. My phone though did receive it correctly.

The scli.log file is just a long list of those critical errors showing timestamps, the messages and the "no sender" bit.

**Comment by s3rvant** [comment]
Okay I think the empty recipient thing was an issue with signal-cli because after clearing out its data and re-linking I can now both send and receive successfully :)

Prior to the re-link when I ran signal-cli receive "got receipt" envelopes but never received any body text".

**Comment by isamert** [comment]
I'm glad it's working now. Sometimes you just need to burn everything down and just start over :)
